# Generated by Django 2.1.5 on 2019-01-07 00:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="event", unique_together={("code", "user")})
    ]
