# Generated by Django 2.1.5 on 2019-01-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0002_auto_20190107_0023")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("error", "Error"),
                ],
                default="inactive",
                max_length=20,
            ),
        )
    ]
